### ISSUE TITLE
check bài 2

### ISSUE THREAD

**Issue by HaiYenPham** [CuongNT2k/CuongNT2k.github.io#2]
https://github.com/CuongNT2k/CuongNT2k.github.io/blob/32ad816b985badeb02f077bf8b70daa68191687a/index.html#L10

bài ok rồi nhé em! đúng là team chị Yến có khác :v 
Cố gắng phát huy nha!
<3

**Comment by CuongNT2k** [comment]
Vâng! Em cảm ơn :>
